export const categories = [
  //{ id: 1, type: "Tech" },
  { id: 1, type: "Front-end" },
  { id: 2, type: "Back-end" },
  { id: 3, type: "Data-Science" },
  { id: 4, type: "ML/AI" },
  { id: 5, type: "Cyber-security" },
  { id: 6, type: "Cryptocurrency/Bitcoin" },
  { id: 7, type: "Full-stack" },
  { id: 8, type: "Latest Interview Experiences" },
  { id: 9, type: "Yoga/Meditation" },
  { id: 10, type: "Sports" },
  { id: 11, type: "Music" },
  { id: 12, type: "Movies" },
  { id: 13, type: "General" },
];
